version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-backend
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: h2go
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
